# Generated by Django 5.2.15 on 2026-06-27 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=20, unique=True, verbose_name='规则编号')),
                ('dimension', models.CharField(max_length=80, verbose_name='维度')),
                ('module', models.CharField(max_length=120, verbose_name='模块')),
                ('item', models.CharField(max_length=200, verbose_name='条目')),
                ('title', models.CharField(max_length=300, verbose_name='制度项目')),
                ('values', models.JSONField(default=list, verbose_name='可选分值')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='信息来源/渠道')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作风量化规则',
                'verbose_name_plural': '作风量化规则',
                'ordering': ['rule_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='科室/部门名称')),
                ('ding_department_id', models.CharField(blank=True, max_length=80, verbose_name='钉钉部门ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='portal.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '科室/部门',
                'verbose_name_plural': '科室/部门',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='姓名')),
                ('employee_no', models.CharField(max_length=40, unique=True, verbose_name='工号')),
                ('role', models.CharField(choices=[('department_admin', '部门行政人员'), ('manager', '管理人员'), ('instructor', '培训教员'), ('student', '飞行学员')], default='student', max_length=30, verbose_name='角色')),
                ('position', models.CharField(blank=True, max_length=80, verbose_name='岗位')),
                ('mobile', models.CharField(blank=True, max_length=30, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('ding_user_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='钉钉UserId')),
                ('ding_union_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='钉钉UnionId')),
                ('is_active', models.BooleanField(default=True, verbose_name='在用')),
                ('can_manage_conduct', models.BooleanField(default=False, verbose_name='可管理作风分')),
                ('excluded_from_conduct_score', models.BooleanField(default=False, verbose_name='不计作风分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='portal.department', verbose_name='所属科室')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '人员档案',
                'verbose_name_plural': '人员档案',
                'ordering': ['department__sort_order', 'employee_no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='dingtalk', max_length=40, verbose_name='登录方式')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='浏览器/客户端')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audits', to='portal.personprofile', verbose_name='人员')),
            ],
            options={
                'verbose_name': '登录审计',
                'verbose_name_plural': '登录审计',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('S1', 'S1 基础理论'), ('S2', 'S2 模拟机训练'), ('S3', 'S3 本场训练'), ('S4', 'S4 跟飞训练')], default='S1', max_length=10, verbose_name='阶段')),
                ('class_name', models.CharField(blank=True, max_length=80, verbose_name='班级/队别')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入队日期')),
                ('initial_score', models.IntegerField(default=100, verbose_name='初始作风分')),
                ('current_score', models.IntegerField(default=100, verbose_name='当前作风分')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='portal.personprofile', verbose_name='人员档案')),
            ],
            options={
                'verbose_name': '学员档案',
                'verbose_name_plural': '学员档案',
                'ordering': ['stage', 'person__employee_no'],
            },
        ),
        migrations.CreateModel(
            name='ConductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_delta', models.IntegerField(verbose_name='调整分值')),
                ('reason', models.TextField(blank=True, verbose_name='补充说明')),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='发生日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduct_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='portal.conductrule', verbose_name='制度项目')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_records', to='portal.studentprofile', verbose_name='学员')),
            ],
            options={
                'verbose_name': '作风分记录',
                'verbose_name_plural': '作风分记录',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
    ]
