# Generated by Django 5.2.15 on 2026-06-29 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_systemsetting_operationaudit_resourcecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='资料名称')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='知识分类')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='版本号')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('visibility', models.CharField(choices=[('all', '全员可问'), ('staff', '管理人员/教员可问'), ('managers', '仅管理人员可问')], default='all', max_length=20, verbose_name='可见范围')),
                ('file', models.FileField(blank=True, upload_to='knowledge_documents/%Y/%m/', verbose_name='原始文件')),
                ('content', models.TextField(blank=True, verbose_name='文本内容')),
                ('summary', models.TextField(blank=True, verbose_name='资料摘要')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='维护人')),
            ],
            options={
                'verbose_name': 'AI知识库资料',
                'verbose_name_plural': 'AI知识库资料',
                'ordering': ['category', 'title', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=240, verbose_name='片段标题')),
                ('content', models.TextField(verbose_name='片段内容')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='portal.knowledgedocument', verbose_name='所属资料')),
            ],
            options={
                'verbose_name': 'AI知识片段',
                'verbose_name_plural': 'AI知识片段',
                'ordering': ['document', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(blank=True, verbose_name='回答')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='来源')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='模型')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提问时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_queries', to=settings.AUTH_USER_MODEL, verbose_name='提问人')),
            ],
            options={
                'verbose_name': 'AI问答记录',
                'verbose_name_plural': 'AI问答记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
